# Generated by Django 3.1.4 on 2021-01-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('desc', models.TextField(max_length=1000)),
                ('startbid', models.IntegerField()),
                ('image', models.URLField()),
                ('categories', models.CharField(max_length=64)),
            ],
        ),
    ]
