# Generated by Django 3.1.4 on 2021-01-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210124_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='categories',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
