# Generated by Django 3.1.4 on 2021-01-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210124_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='categories',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='auctionlist',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
