# Generated by Django 3.1.4 on 2021-01-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210124_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlist',
            old_name='currentbid',
            new_name='startingbid',
        ),
    ]
