# Generated by Django 3.1.4 on 2021-01-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210124_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userlist',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
    ]
