# Generated by Django 3.1.4 on 2021-01-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_userlist_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='categories',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
